version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Configuraci칩n de Nginx
      - ./src/html:/var/www/html          # Archivos est치ticos
    depends_on:
      - php
      - db

  php:
    image: php:8-fpm
    volumes:
      - ./src/php:/var/www/html           # C칩digo PHP
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mi_db
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # Scripts SQL iniciales

  chat:
    image: node:18
    working_dir: /app
    volumes:
      - ./src/chat:/app                     # C칩digo del chat (WebSocket)
    ports:
      - "3000:3000"
    command: ["npm", "start"]
